const postTypes = {
    ADD_NEW_POST: "ADD_NEW_POST",
    DELETE_POST: "DELETE_POST",
    INCREMENT_LIKES: "INCREMENT_LIKES",
    GET_COMMENT: "GET_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT",
    UPDATE_POST: "UPDATE_POST",
    GET_POSTS: "GET_POSTS",
    LOAD_POSTS: "LOAD_POSTS",
}

export default postTypes;