const mainUserTypes = {
    SIGN_UP_START: "SIGN_UP_START",
    USER_INFO_START: "USER_INFO_START",
    GET_USER_POST: "GET_USER_POST",
    LOADING_USER_POST: "LOADING_USER_POST",
    LOADING_USER_NOTIFICATION: "LOADING_USER_NOTIFICATION",
    NEW_NOTIFICATION_SEEN: "NEW_NOTIFICATION_SEEN",
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: "SIGN_IN_FAIL",
    SIGN_UP_FAIL: "SIGN_UP_FAIL",
    SIGN_OUT: 'SIGN_OUT',
    SIGN_UP_TRUE: 'SIGN_UP_TRUE',
    SIGN_UP_FALSE: 'SIGN_UP_FALSE',
    CHECK_CURRENT_USER: "CHECK_CURRENT_USER",
    CHANGE_IN_CURRENT_USER: "CHANGE_IN_CURRENT_USER",
    CHANGE_IN_CURRENT_POST: "CHANGE_IN_CURRENT_POST",
    ADD_FOLLOWING: "ADD_FOLLOWING",
    DELETE_FOLLOWING: "DELETE_FOLLOWING",
}


export default mainUserTypes;