const userTypes = {
    LOAD_PROFILE: "LOAD_PROFILE",
    USER_PROFILE_SCREEN_LOADED: "USER_PROFILE_SCREEN_LOADED",
    LOADED_PROFILE: "LOADED_PROFILE",
    INCREMENT_LIKES: "INCREMENT_LIKES",
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT",
    CHANGE_IN_NEW_USER: "CHANGE_IN_NEW_USER",
    ADD_FOLLOWER: "ADD_FOLLOWER",
    DELETE_FOLLOWER: "DELETE_FOLLOWER",
    NO_PAGE_FOUND: "NO_PAGE_FOUND",
    USER_POST_LOADED: "USER_POST_LOADED",
}

export default userTypes;