const userTypes = {
    LOAD_PROFILE: "LOAD_PROFILE",
    LOAD_PROFILE_BY_SEARCH: "LOAD_PROFILE_BY_SEARCH",
    USER_PROFILE_SCREEN_LOADED: "USER_PROFILE_SCREEN_LOADED",
    PROFILE_LOADED_BY_SEARCH: "PROFILE_LOADED_BY_SEARCH",
    PROFILE_LOADED_BY_CLICK: "PROFILE_LOADED_BY_CLICK",
    LOADED_PROFILE: "LOADED_PROFILE",
    INCREMENT_LIKES: "INCREMENT_LIKES",
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT",
    CHANGE_IN_NEW_USER: "CHANGE_IN_NEW_USER",
    CHANGE_IN_OTHER_POST: "CHANGE_IN_OTHER_POST",    
    ADD_FOLLOWER: "ADD_FOLLOWER",
    DELETE_FOLLOWER: "DELETE_FOLLOWER",
    NO_PAGE_FOUND: "NO_PAGE_FOUND",
}

export default userTypes;